<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>true</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sapphire.Auth.Domain\Sapphire.Auth.Domain.csproj" />
    <ProjectReference Include="..\Sapphire.Auth.Application\Sapphire.Auth.Application.csproj" />
    <ProjectReference Include="..\..\..\shared\Sapphire.Shared.Kernel\Sapphire.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\shared\Sapphire.Shared.Messaging\Sapphire.Shared.Messaging.csproj" />
    <ProjectReference Include="..\..\..\shared\Sapphire.Shared.Security\Sapphire.Shared.Security.csproj" />
    <ProjectReference Include="..\..\..\shared\Sapphire.Shared.Abstractions\Sapphire.Shared.Abstractions.csproj" />
  </ItemGroup>

</Project>
